/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/quizzes/': RouteRecordInfo<'/quizzes/', '/quizzes', Record<never, never>, Record<never, never>>,
    '/quizzes/particle-quiz': RouteRecordInfo<'/quizzes/particle-quiz', '/quizzes/particle-quiz', Record<never, never>, Record<never, never>>,
    '/reference/german-verbs': RouteRecordInfo<'/reference/german-verbs', '/reference/german-verbs', Record<never, never>, Record<never, never>>,
    '/reference/separable-rules': RouteRecordInfo<'/reference/separable-rules', '/reference/separable-rules', Record<never, never>, Record<never, never>>,
  }
}
